# Generated by Django 5.1.6 on 2025-02-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=12, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=12, max_digits=15)),
            ],
        ),
    ]
