# Generated by Django 5.1.6 on 2025-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
