# Generated by Django 5.1.6 on 2025-04-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='owner',
        ),
    ]
