# Generated by Django 5.1.6 on 2025-04-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_created_by_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='priority',
        ),
    ]
