# Generated by Django 5.1.6 on 2025-04-27 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_goal_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
