# Generated by Django 5.1.6 on 2025-04-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_goal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
