# Generated by Django 5.1.6 on 2025-04-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_goal_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
