# Generated by Django 5.1.6 on 2025-05-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_update_date_alter_task_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
