# Generated by Django 5.1.6 on 2025-05-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, to='core.resource'),
        ),
    ]
